(function (global) {
  "use strict";
  var esc = UI.esc;
  var D = APP_DATA;

  var WF_STEPS = ["Draft", "Submitted", "Approved"];

  function render(state) {
    var bank = Store.findBank(state.finalReportBankId) || state.banks[0];
    var relatedAlerts = state.alerts.filter(function (a) { return a.bankId === bank.id; });
    var violations = relatedAlerts.filter(function (a) { return a.status !== "Closed"; });
    var status = state.finalReportStatus;
    var currentIdx = WF_STEPS.indexOf(status);

    var wfHtml = WF_STEPS.map(function (s, i) {
      var cls = i < currentIdx ? "done" : i === currentIdx ? "current" : "";
      return '<div class="wf-step ' + cls + '"><div class="wf-line"></div><div class="wf-dot">' + (i < currentIdx ? "✓" : i + 1) + "</div><div class=\"wf-label\">" + s + "</div></div>";
    }).join("");

    var severity = violations.some(function (a) { return a.severity === "Critical"; })
      ? "Critical"
      : violations.some(function (a) { return a.severity === "Medium"; })
      ? "Medium"
      : violations.length
      ? "Low"
      : "None";

    var execSummary =
      violations.length === 0
        ? bank.name + " reported a Capital Adequacy Ratio of " + bank.car.toFixed(1) + "% and a Liquidity Coverage Ratio of " + bank.lcr + "% for the current period, both within regulatory limits. No open violations were identified by the automated supervision pipeline. No further action is required at this time."
        : "During the Q3 2025 reporting cycle, " + bank.name + " triggered " + violations.length + " open supervisory alert(s), including " +
          violations
            .slice(0, 3)
            .map(function (a) { return a.indicator + " (" + a.severity + ")"; })
            .join(", ") +
          ". These findings were generated by the Rule Matching, Anomaly Detection, and Cross-Bank Pattern Analysis agents and reviewed by the assigned supervisor. This report documents the findings, supporting evidence, and recommended regulatory action.";

    var violationsList = violations.length
      ? "<ul style=\"margin:0;padding-left:18px;\">" +
        violations.map(function (a) { return "<li style=\"margin-bottom:6px;\">" + esc(a.indicator) + " — " + esc(a.description) + " (" + esc(a.severity) + ", " + a.confidence + "% confidence)</li>"; }).join("") +
        "</ul>"
      : "<p>No open violations for this reporting period.</p>";

    var evidenceList = violations.length
      ? "<ul style=\"margin:0;padding-left:18px;\">" +
        violations
          .map(function (a) {
            return a.evidence.map(function (e) { return "<li>" + esc(a.indicator) + ": " + esc(e) + "</li>"; }).join("");
          })
          .join("") +
        "</ul>"
      : "<p>No supporting evidence required.</p>";

    var recommended = violations.length
      ? violations.some(function (a) { return a.severity === "Critical"; })
        ? "Escalate to on-site examination and request a capital/liquidity restoration plan within 30 days."
        : "Request supporting documentation and schedule a follow-up review within 60 days."
      : "No action required; continue routine quarterly monitoring.";

    var bankOptions = state.banks
      .map(function (b) { return '<option value="' + b.id + '" ' + (b.id === bank.id ? "selected" : "") + ">" + esc(b.name) + "</option>"; })
      .join("");

    return (
      "" +
      UI.eyebrow("05", "Regulatory Output") +
      '<h1 class="page-title">Final Reports</h1>' +
      '<p class="page-sub">Structured regulatory report compiled from agent findings, ready for supervisor submission and approval.</p>' +
      UI.disclaimer() +
      '<div class="filters-row">' +
      '<div class="field"><label for="fr-bank">Bank</label><select class="select" id="fr-bank" data-action="set-final-bank">' + bankOptions + "</select></div>" +
      "</div>" +
      '<div class="workflow-steps">' + wfHtml + "</div>" +
      '<div class="report-preview">' +
      '<div class="eyebrow"><span class="num">05.1</span><span class="label">Regulatory Report Preview</span></div>' +
      '<div style="font-size:19px;font-weight:700;margin-bottom:2px;">' + esc(bank.name) + " — Q3 2025 Supervisory Report</div>" +
      '<div style="font-size:11.5px;color:var(--text-faint);margin-bottom:10px;">Severity Level: ' + UI.severityBadge(severity === "None" ? "Closed" : severity) + " &nbsp; Status: " + UI.statusBadge(status === "Draft" ? "Review Required" : "Compliant") + "</div>" +
      "<h3>Executive Summary</h3><p>" + esc(execSummary) + "</p>" +
      "<h3>Violations</h3>" + violationsList +
      "<h3>Supporting Evidence</h3>" + evidenceList +
      "<h3>Regulatory References</h3><p><i>" + esc(D.REGULATORY_REFERENCE.excerpt) + "</i><br/><span style=\"font-size:11px;color:var(--text-faint);\">" + esc(D.REGULATORY_REFERENCE.source) + "</span></p>" +
      "<h3>Severity Level</h3><p>" + esc(severity) + "</p>" +
      "<h3>Recommended Action</h3><p>" + esc(recommended) + "</p>" +
      "</div>" +
      '<div class="actions-row">' +
      '<button class="btn btn-secondary" data-action="download-report" data-format="PDF">Download PDF</button>' +
      '<button class="btn btn-secondary" data-action="download-report" data-format="Excel">Export to Excel</button>' +
      '<button class="btn btn-primary" data-action="submit-final-report" ' + (status !== "Draft" ? "disabled" : "") + ">" + (status === "Draft" ? "Submit for Review" : status === "Submitted" ? "Awaiting Approval…" : "Approved") + "</button>" +
      "</div>"
    );
  }

  global.Views = global.Views || {};
  global.Views.finalReports = render;
})(window);
